name: wordpreesapp
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_bottom_navigation_bar: ^1.1.0+1

  provider: ^6.0.5
  dio: ^5.1.1
  intl: ^0.18.1
  # collection: ^1.17.0
  # flutter_inappwebview: ^5.7.2+3
  # shamsi_date: ^1.0.1
  # persistent_bottom_nav_bar: ^5.0.2
  # flutter_native_splash: ^2.3.1
  # loading_animation_widget: ^1.2.0+4
  # flutter_secure_storage: ^8.0.0
  

  cupertino_icons: ^1.0.2
  page_transition: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  # assets:
    # - assets/images/
 
  # example:
  fonts:
    - family: iranSans
      fonts:
        - asset: assets/fonts/IRANSans.ttf
    - family: Lalezar
      fonts:
        - asset: assets/fonts/Lalezar.ttf
    - family: Yekanplus
      fonts:
        - asset: assets/fonts/YEKAN_PLUS.TTF
    - family: nazanin
      fonts:
        - asset: assets/fonts/B-NAZANIN.TTF
    - family: yagut
      fonts:
        - asset: assets/fonts/B Yagut_0.ttf
    - family: yagut_b
      fonts:
        - asset: assets/fonts/B Yagut Bold_0.ttf